/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans:    ["'Inter'", '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        grotesk: ["'Space Grotesk'", 'sans-serif'],
        mono:    ["'JetBrains Mono'", 'monospace'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background:  'hsl(var(--background))',
        foreground:  'hsl(var(--foreground))',
        card: {
          DEFAULT:    'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT:    'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT:    'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT:    'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT:    'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT:    'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT:    'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input:  'hsl(var(--input))',
        ring:   'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT:              'hsl(var(--sidebar-background))',
          foreground:           'hsl(var(--sidebar-foreground))',
          primary:              'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent:               'hsl(var(--sidebar-accent))',
          'accent-foreground':  'hsl(var(--sidebar-accent-foreground))',
          border:               'hsl(var(--sidebar-border))',
          ring:                 'hsl(var(--sidebar-ring))',
        },
        /* ── Brand Palette — Dark Teal+Red ── */
        brand: {
          navy:          '#00b4b4',
          'navy-light':  '#00d4d4',
          'navy-soft':   '#00a0a0',
          'navy-pale':   'rgba(0,180,180,0.1)',
          crimson:       '#e02347',
          'crimson-light':'#ff3358',
          'crimson-soft': '#ff6680',
          'crimson-pale': 'rgba(224,35,71,0.1)',
          sky:           '#22d3ee',
          'sky-soft':    '#67e8f9',
          'sky-pale':    'rgba(34,211,238,0.1)',
          emerald:       '#10b981',
          'emerald-soft':'#34d399',
          amber:         '#f59e0b',
          'amber-soft':  '#fbbf24',
          rose:          '#e02347',
          'rose-soft':   '#ff6680',
          teal:          '#00b4b4',
          'teal-light':  '#00d4d4',
        },
        /* Legacy support */
        navy:    { DEFAULT: '#00b4b4', light: '#00d4d4', soft: '#00a0a0', pale: 'rgba(0,180,180,0.1)' },
        crimson: { DEFAULT: '#e02347', light: '#ff3358', soft: '#ff6680', pale: 'rgba(224,35,71,0.1)' },
        teal:    { DEFAULT: '#00b4b4', light: '#00d4d4' },
      },
      boxShadow: {
        'navy-sm':     '0 2px 10px rgba(30,45,110,0.12)',
        'navy-md':     '0 4px 20px rgba(30,45,110,0.18)',
        'navy-lg':     '0 8px 40px rgba(30,45,110,0.22)',
        'navy-glow':   '0 0 20px rgba(30,45,110,0.25)',
        'crimson-sm':  '0 2px 10px rgba(196,30,58,0.15)',
        'crimson-md':  '0 4px 20px rgba(196,30,58,0.22)',
        'crimson-glow':'0 0 20px rgba(196,30,58,0.3)',
        'sky-sm':      '0 2px 10px rgba(14,165,233,0.15)',
        'sky-glow':    '0 0 20px rgba(14,165,233,0.3)',
        'emerald-sm':  '0 2px 10px rgba(5,150,105,0.15)',
        'emerald-glow':'0 0 20px rgba(5,150,105,0.3)',
        'card':        '0 2px 12px rgba(30,45,110,0.07)',
        'card-hover':  '0 6px 24px rgba(30,45,110,0.14)',
        /* Legacy */
        'purple-sm':   '0 2px 10px rgba(30,45,110,0.12)',
        'purple-md':   '0 4px 20px rgba(30,45,110,0.18)',
        'blue-sm':     '0 2px 10px rgba(30,45,110,0.12)',
        'blue-md':     '0 4px 20px rgba(30,45,110,0.18)',
        'red-sm':      '0 2px 10px rgba(196,30,58,0.15)',
        'red-glow':    '0 0 20px rgba(196,30,58,0.3)',
        'lilac-sm':    '0 2px 10px rgba(30,45,110,0.12)',
        'lilac-md':    '0 4px 20px rgba(30,45,110,0.18)',
        'violet-sm':   '0 2px 10px rgba(30,45,110,0.12)',
        'violet-md':   '0 4px 20px rgba(30,45,110,0.18)',
        'violet-glow': '0 0 20px rgba(30,45,110,0.25)',
        'indigo-sm':   '0 2px 10px rgba(30,45,110,0.12)',
        'cyan-sm':     '0 2px 10px rgba(14,165,233,0.15)',
        'cyan-glow':   '0 0 20px rgba(14,165,233,0.3)',
        'rose-sm':     '0 2px 10px rgba(196,30,58,0.15)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to:   { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to:   { height: '0' },
        },
        'pulse-navy': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(30,45,110,0.3)' },
          '50%':      { boxShadow: '0 0 0 8px rgba(30,45,110,0)' },
        },
        'pulse-crimson': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(196,30,58,0.3)' },
          '50%':      { boxShadow: '0 0 0 8px rgba(196,30,58,0)' },
        },
        'network-flow': {
          '0%':   { backgroundPosition: '0 0' },
          '100%': { backgroundPosition: '60px 60px' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-6px)' },
        },
        'shimmer': {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'accordion-down':   'accordion-down 0.2s ease-out',
        'accordion-up':     'accordion-up 0.2s ease-out',
        'pulse-navy':       'pulse-navy 2s ease-in-out infinite',
        'pulse-crimson':    'pulse-crimson 2s ease-in-out infinite',
        'network-flow':     'network-flow 4s linear infinite',
        'float':            'float 4s ease-in-out infinite',
        'shimmer':          'shimmer 2s infinite',
        /* Legacy aliases */
        'glow-pulse':       'pulse-navy 2.5s ease-in-out infinite',
        'glow-pulse-red':   'pulse-crimson 2.5s ease-in-out infinite',
        'glow-pulse-blue':  'pulse-navy 2.5s ease-in-out infinite',
        'glow-pulse-green': 'pulse-navy 2.5s ease-in-out infinite',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    'bg-navy', 'text-navy', 'border-navy',
    'bg-crimson', 'text-crimson', 'border-crimson',
    'bg-brand-navy', 'text-brand-navy',
    'bg-brand-crimson', 'text-brand-crimson',
    'bg-brand-sky', 'text-brand-sky',
    'bg-brand-emerald', 'text-brand-emerald',
    'bg-brand-amber', 'text-brand-amber',
    'bg-brand-rose', 'text-brand-rose',
    /* Legacy safelist */
    'bg-lilac', 'text-lilac', 'border-lilac',
    'bg-violet', 'text-violet', 'border-violet',
    'bg-brand-violet', 'text-brand-violet',
    'bg-brand-indigo', 'text-brand-indigo',
    'bg-brand-cyan', 'text-brand-cyan',
    'bg-brand-purple', 'text-brand-purple',
    'bg-brand-blue', 'text-brand-blue',
    'bg-brand-red', 'text-brand-red',
    'shadow-navy-glow', 'shadow-crimson-glow', 'shadow-sky-glow',
    'shadow-emerald-glow', 'shadow-rose-sm',
    'shadow-purple-glow', 'shadow-blue-glow', 'shadow-red-glow',
    'shadow-violet-glow', 'shadow-indigo-glow', 'shadow-cyan-glow',
  ],
};
